--populate Region table
INSERT INTO REGIONS(name) VALUES('African')
INSERT INTO REGIONS(name) VALUES('American')
INSERT INTO REGIONS(name) VALUES('Asian')
INSERT INTO REGIONS(name) VALUES('European')
INSERT INTO REGIONS(name) VALUES('Oceanic')

--populate Religion table
INSERT INTO RELIGIONS (name) VALUES('Christianity')
INSERT INTO RELIGIONS (name) VALUES('Judaism')
INSERT INTO RELIGIONS (name) VALUES('Islam')
INSERT INTO RELIGIONS (name) VALUES('Hinduism')
INSERT INTO RELIGIONS (name) VALUES('Buddhism')
INSERT INTO RELIGIONS (name) VALUES('None')


--populate Type table
INSERT INTO TYPES (name) VALUES ('Acid Regulator')
INSERT INTO TYPES (name) VALUES ('Anticaking Agent')
INSERT INTO TYPES (name) VALUES ('Antifoaming Agent')
INSERT INTO TYPES (name) VALUES ('Antioxidant')
INSERT INTO TYPES (name) VALUES ('Carrier')
INSERT INTO TYPES (name) VALUES ('Color')
INSERT INTO TYPES (name) VALUES ('Emulsifiers')
INSERT INTO TYPES (name) VALUES ('Firming Agent')
INSERT INTO TYPES (name) VALUES ('Flavor Enhancer')
INSERT INTO TYPES (name) VALUES ('Foaming Agent')
INSERT INTO TYPES (name) VALUES ('Gelling Agent')
INSERT INTO TYPES (name) VALUES ('Glazing Agent')
INSERT INTO TYPES (name) VALUES ('Humectant')
INSERT INTO TYPES (name) VALUES ('Preservative')
INSERT INTO TYPES (name) VALUES ('Raising Agent')
INSERT INTO TYPES (name) VALUES ('Sequestrant')
INSERT INTO TYPES (name) VALUES ('Stabilizer')
INSERT INTO TYPES (name) VALUES ('Sweetener')
INSERT INTO TYPES (name) VALUES ('Thickener')
INSERT INTO TYPES (name) VALUES ('Spice')
INSERT INTO TYPES (name) VALUES ('Sauce')
INSERT INTO TYPES (name) VALUES ('Vegetable')
INSERT INTO TYPES (name) VALUES ('Fruit')
INSERT INTO TYPES (name) VALUES ('Meat')
INSERT INTO TYPES (name) VALUES ('Flavor Agent')